services:
  app:
    build:
      context: .
    ports:
      - 8080:8080
      - 8081:8081
    depends_on:
      - db
    networks:
      - network

  db:
    image: mysql:9
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: iis
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - ./.mysql/data:/var/lib/mysql
    networks:
      - network

networks:
  network:
    driver: bridge